name: Testes RestAssured

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do código
    - name: Check out o código
      uses: actions/checkout@v2

    # 2. Configuração do JDK 17 usando a distribuição Adoptium (temurin)
    - name: Configurar JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'  # Usa a distribuição Temurin para JDK 17

    # 3. Instalar Maven
    - name: Instalar Maven
      run: |
        sudo apt-get update
        sudo apt-get install maven

    # 4. Baixar dependências e rodar os testes com Maven
    - name: Executar testes com Maven
      run: mvn clean test 
