name: Testes RestAssured

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do código
    - name: Check out o código
      uses: actions/checkout@v2

    # 2. Configuração do JDK (Java)
    - name: Configurar JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    # 3. Instalar o Maven (se não estiver usando o Gradle)
    - name: Instalar Maven
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        maven-version: '3.8.4'

    # 4. Baixar dependências e rodar os testes
    - name: Executar testes com Maven
      run: mvn clean test -DskipTests=false
